import React, { useEffect, useState } from "react";
import PropTypes from "prop-types";
import axios from "axios";

import { Card, FormField, Loader } from "../components";

const RenderCards = ({ data, title }) => {
  if (data?.length > 0) {
    return data.map((post) => <Card key={post._id} {...post} />);
  }

  return (
    <h2 className="mt-5 font-bold text-violet-400 text-xl uppercase">
      {title}
    </h2>
  );
};

function Home() {
  const [loading, setLoading] = useState(false);
  const [allPosts, setAllPosts] = useState(null);

  const [searchText, setSearchText] = useState("");
  const [searchedResults, setSearchedResults] = useState(null);
  const [searchTimeout, setSearchTimeout] = useState(null);

  useEffect(() => {
    const fecthPosts = async () => {
      setLoading(true);

      try {
        const response = await axios.get("http://localhost:8080/api/v1/posts");
        if (response.statusText === "OK") {
          setAllPosts(response.data.data.reverse());
        }
      } catch (error) {
        alert("somethings failed");
      } finally {
        setLoading(false);
      }
    };
    fecthPosts();
  }, []);

  const handleSearchChange = (e) => {
    clearTimeout(searchTimeout);
    setSearchText(e.target.value);

    setSearchTimeout(
      setTimeout(() => {
        const searchResults = allPosts.filter(
          (item) =>
            item.name.toLowerCase().includes(searchText.toLowerCase()) ||
            item.prompt.toLowerCase().includes(searchText.toLowerCase())
        );

        setSearchedResults(searchResults);
      }, 500)
    );
  };

  return (
    <section className="max-w-7x1 mx-auto">
      <div>
        <h1 className="font-extrabold text-gray-900 text-[32px]">
          The Community Showcase
        </h1>
        <p className="mt-2 text-gray-400 text-[14px] max-w-[500px]">
          Browse trougth a colection of imaginative and visually stunning images
          generated by DALL-E AI
        </p>
      </div>
      <div className="mt-16">
        <FormField
          LabelName="Search posts"
          type="text"
          name="text"
          placeholder="Ex: fish, dog, a horse win the rain"
          value={searchText}
          handleChange={handleSearchChange}
        />
      </div>
      <div className="mt-10">
        {loading ? (
          <div className="flex justify-center items-center">
            <Loader />
          </div>
        ) : (
          <>
            {searchText && (
              <h2 className="font-medium text-gray-500 text-xl mb-3">
                Showing results for{" "}
                <span className="text-violet-400 font-bold">{`"${searchText}"`}</span>
              </h2>
            )}
            <div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3">
              {searchText ? (
                <RenderCards
                  data={searchedResults}
                  title="No search results found"
                />
              ) : (
                <RenderCards data={allPosts} title="No posts found" />
              )}
            </div>
          </>
        )}
      </div>
    </section>
  );
}

RenderCards.propTypes = {
  data: PropTypes.array,
  title: PropTypes.string,
};

export default Home;
